services:
  db_postgres:
    container_name: db_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - main-network

  nginxProxyManager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      # Postgres connection params:
      DB_POSTGRES_HOST: db_postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: npm
      DB_POSTGRES_PASSWORD: npm
      DB_POSTGRES_NAME: npm
    volumes:
      - ./nginxProxyManager/data:/data
      - ./nginxProxyManager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_postgres
    networks:
      - main-network
