services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init-scripts:/docker-entrypoint-initdb.d
    networks:
      - main-network

  nginxProxyManager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: npm
      POSTGRES_PASSWORD: npm
      POSTGRES_NAME: npm
    volumes:
      - ./nginxProxyManager/data:/data
      - ./nginxProxyManager/letsencrypt:/etc/letsencrypt
    depends_on:
      - postgres
    networks:
      - main-network

networks:
  main-network:
    external: true